### ISSUE TITLE
Setup React Router

### ISSUE THREAD

**Issue by zaycation** [zaycation/SimpleSnake#2]
React Router Dom is already currently installed via NPM. Set up simple react router config for the navbar options for opening DevLogs, About, and the BTC/XMR donation pages.

**Comment by Narinder84** [comment]
hey, I worked on it...!!

**Comment by zaycation** [comment]
> hey, I worked on it...!!

Great thanks! Let me know when you push the new changes bud.

Here's a link to our discord as well if you want to join: https://discord.gg/UQXg96rjm6
